micronaut:
  application:
    name: micronaut
  security:
      enabled: false
  session:
    http:
      cookie: true
      header: true
  server:
    port: 8081
netty:
  default:
    allocator:
      max-order: 3
